backend:
  name: git-gateway
  repo: byvasco/amore

media_folder: static/assets
public_folder: /assets

collections:
  - name: animals
    label: Animals
    folder: content/animals
    create: true
    fields:
      - { name: name, label: Nome }
      - {
        name: race,
        label: Raça,
        widget: select,
        options: [
          "Rafeiro Comum",
          "Rafeiro Comum",
          "Rafeiro Comum",
          "Rafeiro Comum"
        ]
      }

      - {
        name: age,
        label: Idade,
        widget: select,
        options: [
          "Bebé",
          "Jovem",
          "Adulto",
          "Idoso"
        ]
      }

      - {
        name: sex,
        label: Sexo,
        widget: select,
        options: [
          "Macho",
          "Fêmea"
        ]
      }

      - {
        name: size,
        label: Porte,
        widget: select,
        options: [
          "Pequeno",
          "Médio",
          "Grande"
        ]
      }

      - {
        name: fur,
        label: Pêlo,
        widget: select,
        options: [
          "Preto",
          "Branco",
          "Amarelo",
          "Outra cor"
        ]
      }

      - {
        name: sterelized,
        label: Esterelizado,
        widget: boolean,
        required: false
      }

      - {
        name: vaccines,
        label: Vacinas em dia,
        widget: boolean,
        required: false
      }

      - {
        name: dewormed,
        label: Desparasitado,
        widget: boolean,
        required: false
      }

      - name: images
        label: Images
        widget: list
        field: { label: Image, name: image, widget: image }

      - { name: body, label: Body, widget: markdown }